name: Official SonarQube (Server, Cloud) Scan
description: >
  Scan your code with SonarQube Server and Cloud to detect 
  issues in 30+ languages. (Formerly SonarQube and SonarCloud)
branding:
  icon: check
  color: green
inputs:
  args:
    description: Additional arguments to the Sonar Scanner CLI
    required: false
  projectBaseDir:
    description: Set the sonar.projectBaseDir analysis property
    required: false
  scannerVersion:
    description: Version of the Sonar Scanner CLI to use
    required: false
    default: 6.2.1.4610
  scannerBinariesUrl:
    description: URL to download the Sonar Scanner CLI binaries from
    required: false
    default: https://binaries.sonarsource.com/Distribution/sonar-scanner-cli
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v4
      with:
        path: ./actions
    - uses: ./actions/sanity-checks
      with:
        projectBaseDir: ${{ inputs.projectBaseDir }}
    - uses: ./actions/install-sonar-scanner
      with:
        scannerVersion: ${{ inputs.scannerVersion }}
        scannerBinariesUrl: ${{ inputs.scannerBinariesUrl }}
    - uses: ./actions/run-sonar-scanner
      with:
        args: ${{ inputs.args }}
        projectBaseDir: ${{ inputs.projectBaseDir }}
        scannerVersion: ${{ inputs.scannerVersion }}
